In [2]:
import pandas as pd

caminho_arquivo = r"H:\python\3-etapa\atividade_4\CD2022_Populacao_2010_Compatibilizada_20231222 (1).xlsx"

df = pd.read_excel(caminho_arquivo, sheet_name="Municípios", header=2)

df = df.drop(columns=[c for c in df.columns if "Unnamed" in str(c)])
df = df.dropna(subset=["UF"]).reset_index(drop=True)

df = df.rename(columns={
    "População Município 2010\n(Sinopse)": "Pop_2010_Sinopse",
    "População 2010 (Alterações de Limites até 2022)1": "Pop_2010_Compatibilizada",
    "População Censo 2022": "Pop_2022"
})

print(df.head())

   UF  COD. UF  COD. MUNIC      NOME DO MUNICÍPIO  Pop_2010_Sinopse  \
0  RO     11.0        15.0  Alta Floresta D'Oeste           24392.0
1  RO     11.0        23.0              Ariquemes           90353.0
2  RO     11.0        31.0                 Cabixi            6313.0
3  RO     11.0        49.0                 Cacoal           78574.0
4  RO     11.0        56.0             Cerejeiras           17029.0

   Pop_2010_Compatibilizada  Pop_2022
0                   24392.0   21494.0
1                   90353.0   96833.0
2                    6313.0    5351.0
3                   78574.0   86887.0
4                   17029.0   15890.0

In [4]:
df = df.iloc[0:5570]

In [6]:
df["Dif"] = df["Pop_2022"] - df["Pop_2010_Compatibilizada"]

In [7]:
df

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,Pop_2010_Sinopse,Pop_2010_Compatibilizada,Pop_2022,Dif
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0,-2898.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0,6480.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0,-962.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0,8313.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0,-1139.0
...,...,...,...,...,...,...,...,...
5565,GO,52.0,22005.0,Vianópolis,12548.0,12548.0,14956.0,2408.0
5566,GO,52.0,22054.0,Vicentinópolis,7371.0,7373.0,8768.0,1395.0
5567,GO,52.0,22203.0,Vila Boa,4735.0,4735.0,4215.0,-520.0
5568,GO,52.0,22302.0,Vila Propício,5145.0,5145.0,5815.0,670.0
5569,DF,53.0,108.0,Brasília,2570160.0,2572159.0,2817381.0,245222.0

In [8]:
pop_estado = (
    df.groupby("UF")[["Pop_2010_Compatibilizada", "Pop_2022", "Dif"]]
    .sum()
    .reset_index()
)
pop_estado

    UF  Pop_2010_Compatibilizada    Pop_2022        Dif
0   AC                  733559.0    830018.0    96459.0
1   AL                 3120887.0   3127683.0     6796.0
2   AM                 3483985.0   3941613.0   457628.0
3   AP                  669526.0    733759.0    64233.0
4   BA                14017071.0  14141626.0   124555.0
5   CE                 8451644.0   8794957.0   343313.0
6   DF                 2572159.0   2817381.0   245222.0
7   ES                 3514952.0   3833712.0   318760.0
8   GO                 6001789.0   7056495.0  1054706.0
9   MA                 6574789.0   6776699.0   201910.0
10  MG                19597330.0  20539989.0   942659.0
11  MS                 2449024.0   2757013.0   307989.0
12  MT                 3035122.0   3658649.0   623527.0
13  PA                 7581051.0   8120131.0   539080.0
14  PB                 3766528.0   3974687.0   208159.0
15  PE                 8796055.0   9058931.0   262876.0
16  PI                 3119097.0   3271199.0   152102.0
17  PR                10444526.0  11444380.0   999854.0
18  RJ                15989929.0  16055174.0    65245.0
19  RN                 3168027.0   3302729.0   134702.0
20  RO                 1562409.0   1581196.0    18787.0
21  RR                  450479.0    636707.0   186228.0
22  RS                10693929.0  10882965.0   189036.0
23  SC                 6248436.0   7610361.0  1361925.0
24  SE                 2067852.0   2210004.0   142152.0
25  SP                41262199.0  44411238.0  3149039.0
26  TO                 1383445.0   1511460.0   128015.0

In [9]:
pop_estado.to_csv(r"H:\python\3-etapa\atividade_4\pop_estado.csv", sep =";")

In [10]:
df = df.iloc[0:5570, 3: ]

In [11]:
df

,NOME DO MUNICÍPIO,Pop_2010_Sinopse,Pop_2010_Compatibilizada,Pop_2022,Dif
0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0,-2898.0
1,Ariquemes,90353.0,90353.0,96833.0,6480.0
2,Cabixi,6313.0,6313.0,5351.0,-962.0
3,Cacoal,78574.0,78574.0,86887.0,8313.0
4,Cerejeiras,17029.0,17029.0,15890.0,-1139.0
...,...,...,...,...,...
5565,Vianópolis,12548.0,12548.0,14956.0,2408.0
5566,Vicentinópolis,7371.0,7373.0,8768.0,1395.0
5567,Vila Boa,4735.0,4735.0,4215.0,-520.0
5568,Vila Propício,5145.0,5145.0,5815.0,670.0
5569,Brasília,2570160.0,2572159.0,2817381.0,245222.0

In [12]:
df.to_csv(r"H:\python\3-etapa\atividade_4\pop_cidade.csv", sep =";")